project_id = "bgtlaqprmhrfujaviyiw"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.send-ticket-notification]
verify_jwt = false
